// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAJl9rFruEcuryhR76Hu6Vw6alTfmafYk',
    appId: '1:173139534080:web:e5e84ccf81c991260453e5',
    messagingSenderId: '173139534080',
    projectId: 'triple-m-garage',
    authDomain: 'triple-m-garage.firebaseapp.com',
    storageBucket: 'triple-m-garage.firebasestorage.app',
    measurementId: 'G-DH5RR84MQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6dqma1mW-eP_DiPsbBnc9ikmTe8m8PJw',
    appId: '1:173139534080:android:330b71a39bb5755d0453e5',
    messagingSenderId: '173139534080',
    projectId: 'triple-m-garage',
    storageBucket: 'triple-m-garage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC36bQIsaHOyhb4vt_i599JmrNrSiOPMo4',
    appId: '1:173139534080:ios:e2ec07e90e219c7d0453e5',
    messagingSenderId: '173139534080',
    projectId: 'triple-m-garage',
    storageBucket: 'triple-m-garage.firebasestorage.app',
    iosBundleId: 'com.example.gdpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC36bQIsaHOyhb4vt_i599JmrNrSiOPMo4',
    appId: '1:173139534080:ios:e2ec07e90e219c7d0453e5',
    messagingSenderId: '173139534080',
    projectId: 'triple-m-garage',
    storageBucket: 'triple-m-garage.firebasestorage.app',
    iosBundleId: 'com.example.gdpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAJl9rFruEcuryhR76Hu6Vw6alTfmafYk',
    appId: '1:173139534080:web:153baa278873f8f50453e5',
    messagingSenderId: '173139534080',
    projectId: 'triple-m-garage',
    authDomain: 'triple-m-garage.firebaseapp.com',
    storageBucket: 'triple-m-garage.firebasestorage.app',
    measurementId: 'G-88ZWRCF3LZ',
  );
}
