// lib/main.dart

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';       // For Firebase initialization
import 'firebase_options.dart';                          // Generated by flutterfire configure
import 'package:provider/provider.dart';

// Import your providers
import 'package:gdp_app/providers/booking_provider.dart';
import 'package:gdp_app/providers/user_provider.dart';

// Import your initial screen (e.g., HomeScreen)
import 'package:gdp_app/screens/home_screen.dart';

Future<void> main() async {
  // Ensure widgets and binding are initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the options from firebase_options.dart
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider<BookingProvider>(
          create: (_) => BookingProvider(),
        ),
        ChangeNotifierProvider<UserProvider>(
          create: (_) => UserProvider(),
        ),
      ],
      child: const TripleMGarageApp(),
    ),
  );
}

class TripleMGarageApp extends StatelessWidget {
  const TripleMGarageApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Triple M Garage',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        brightness: Brightness.dark,
        colorScheme: ColorScheme.fromSwatch(
          primarySwatch: Colors.deepPurple,
          brightness: Brightness.dark,
        ).copyWith(
          secondary: const Color(0xFFE94560),
        ),
        primaryColor: const Color(0xFF1A1A2E),
        scaffoldBackgroundColor: const Color(0xFF16213E),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF0F3460),
          titleTextStyle: TextStyle(
            color: Color(0xFFF9F9F9),
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
          iconTheme: IconThemeData(color: Color(0xFFF9F9F9)),
        ),
        drawerTheme: const DrawerThemeData(
          backgroundColor: Color(0xFF1A1A2E),
        ),
        textTheme: const TextTheme(
          bodyMedium: TextStyle(color: Color(0xFFF9F9F9)),
          bodyLarge: TextStyle(color: Color(0xFFF9F9F9)),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFFE94560),
            foregroundColor: const Color(0xFFF9F9F9),
          ),
        ),
      ),
      home: const HomeScreen(), // Adjust to whichever screen you want as the starting page
    );
  }
}
